ci: fix release branch configuration
This fixes the error message in CI:

```
[11:10:00 PM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).
Error: AggregateError:
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/lib/get-error.js:6:10)
        at /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/lib/branches/index.js:44:19
        at Array.reduce (<anonymous>)
        at module.exports (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/lib/branches/index.js:34:46)
        at async run (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js:57:22)
        at async module.exports (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js:260:22)
        at async release (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/src/index.js:28:18)
This may occur if your repository does not have a release branch, such as master.
Your configuration for the problematic branches is [].
```